Semillero/urls.py
from Aplication import views
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.principal),
    path('principal/', views.principal, name='principal'),
    path('agregar-usuario/', views.agregar_usuario, name='agregar_usuario'),
    path('listar-usuarios/', views.listar_usuarios, name='listar_usuarios'),
    path('verificar-carnet/', views.verificar_carnet, name='verificar_carnet'),
    path('usuario/<int:usuario_id>/', views.informacion_usuario, name='informacion_usuario'),
    path('agregar-producto/', views.agregar_producto, name='agregar_producto'),
    path('listar-productos/', views.listar_productos, name='listar_productos'),
    path('producto/<int:producto_id>/', views.informacion_producto, name='informacion_producto'),
    path('entregar-producto/', views.entregar_producto, name='entregar_producto'),
    path('lista-movimientos/', views.lista_movimientos, name='lista_movimientos'),
    path('movimiento/<int:movimiento_id>/', views.informacion_movimiento, name='informacion_movimiento'),
    path('usuarios/', views.usuarios, name='usuarios'),
    path('productos/', views.productos, name='productos'),
    path('movimientos/', views.movimientos, name='movimientos'),
    path('devolver_producto/', views.devolver_producto, name='devolver_producto'),
    path('historial/', views.historial, name='historial'),
    path('historial/<int:historial_id>/', views.informacion_historial, name='informacion_historial'),
    path('eliminar-producto/<int:producto_id>/', views.eliminar_producto, name='eliminar_producto'),
     path('editar-producto/<int:producto_id>/', views.editar_producto, name='editar_producto'),
]

Aplication/models.py
from django.db import models
from django.forms import ValidationError

class Usuario(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=255)
    carrera = models.CharField(max_length=100, choices=[
        ('IngAmbiental', 'Ingeniería Ambiental'),
        ('IngIndustrial', 'Ingeniería Industrial'),
        ('CompIA', 'Ciencias de la Computación e IA'),
        ('IngElectronica', 'Ingeniería Electrónica'),
        ('Matematicas', 'Matemáticas'),
    ])

    carnet = models.CharField(max_length=20, unique=True)
    correo_electronico = models.EmailField(max_length=255, unique=True)

    def __str__(self):
        return self.nombre

    def clean(self):
        # Validación personalizada para garantizar que el correo y el carnet no se repitan
        if Usuario.objects.filter(carnet=self.carnet).exclude(id=self.id).exists():
            raise ValidationError({'carnet': 'Este número de carnet ya está registrado.'})
        
        if Usuario.objects.filter(correo_electronico=self.correo_electronico).exclude(id=self.id).exists():
            raise ValidationError({'correo_electronico': 'Este correo electrónico ya está registrado.'})
    
# en models.py de tu aplicación
class Producto(models.Model):

    OPCIONES_UBICACION = [
        ('A2', 'A2'),
        ('A3', 'A3'),
        ('A4', 'A4'),
        ('A5', 'A5'),
        ('A6', 'A6'),
        ('B1', 'B1'),
        ('B2', 'B2'),
        ('B3', 'B3'),
        ('B4', 'B4'),
        ('B5', 'B5'),
        ('B6', 'B6'),
        ('C3', 'C3'),
        ('C4', 'C4'),
        ('C5', 'C5'),
        ('C6', 'C6'),
        ('C7', 'C7'),
        ('C8', 'C8'),
        ('T1', 'T1'),
        ('T2', 'T2'),
        ('OTRO', 'Otro'),
    ]

    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=255)
    marca = models.CharField(max_length=255)
    modelo = models.CharField(max_length=255)
    codigo = models.CharField(max_length=255)
    ubicacion = models.CharField(max_length=255, choices=OPCIONES_UBICACION, default='')
    otra_ubicacion = models.CharField(max_length=255, blank=True, null=True)
    disponible = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.nombre} - {self.marca} - {self.codigo} - {self.ubicacion} - {self.modelo} - {self.disponible}"

class Movimiento(models.Model):
    usuario = models.ForeignKey('Usuario', on_delete=models.CASCADE)
    producto = models.ForeignKey('Producto', on_delete=models.CASCADE)
    hora_entrega = models.DateTimeField(auto_now_add=True)
    comentario = models.TextField(blank=True, null=True, default='Ningún Comentario')

    def __str__(self):
        return f'Movimiento de {self.usuario} para {self.producto} a las {self.hora_entrega}'

class DevolucionProducto(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    codigo_producto = models.CharField(max_length=50)

    def __str__(self):
        return f"Devolución de {self.producto} - Código: {self.codigo_producto}"

class Historial(models.Model):
    
    tipo = models.CharField(max_length=10)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    usuario = models.ForeignKey('Usuario', on_delete=models.CASCADE)
    fecha_movimiento = models.DateTimeField(auto_now_add=True)
    comentario = models.TextField(blank=True, null=True, default='Ningún Comentario')

    def __str__(self):
        return f"{self.tipo} - {self.producto} - {self.usuario}"

class Inventario(models.Model):
    ActivoFijo = models.CharField(max_length=255)
    Objeto = models.CharField(max_length=255)
    Marca = models.CharField(max_length=255)
    Modelo = models.CharField(max_length=255)
    Ubicacion = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.Objeto} - {self.ActivoFijo} - {self.Marca}"
    

Aplication/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import get_object_or_404, redirect, render
from django.shortcuts import render, redirect
from django.contrib import messages
from Aplication.utils import obtener_datos_para_grafico
from Semillero import settings
from .models import Historial, Movimiento, Producto, Usuario
from .forms import DevolucionProductoForm, UsuarioForm,ProductoForm,EntregaProductoForm,Movimiento
from django.core.mail import send_mail
from django.template.loader import render_to_string

def usuarios(request):
    return render(request, 'pages/usuarios/usuarios.html')

def productos(request):
    return render(request, 'pages/productos/productos.html')

def movimientos(request):
    return render(request, 'pages/movimientos/movimientos.html')

def agregar_usuario(request):
    if request.method == 'POST':
        form = UsuarioForm(request.POST)
        if form.is_valid():
            usuario = form.save(commit=False)
            # Puedes hacer ajustes en el campo id aquí si es necesario
            usuario.save()

            # Renderiza el contenido HTML desde la plantilla
            context = {'user': usuario}  # Puedes pasar datos adicionales a la plantilla si es necesario
            html_content = render_to_string('correos/emailpage.html', context)


                # Envía un correo electrónico de confirmación con contenido HTML
            subject = 'Bienvenido a Nuestra Aplicación'
            from_email = settings.EMAIL_HOST_USER
            recipient_list = [usuario.correo_electronico]

            send_mail(subject, '', from_email, recipient_list, fail_silently=True, html_message=html_content)

            return redirect('listar_usuarios')  # Ajusta según el nombre de tu vista de lista de usuarios
    else:
        form = UsuarioForm()

    return render(request, 'pages/usuarios/formulario_usuario.html', {'form': form})

ICONOS_CARRERA = {
    'IngAmbiental': 'bx bxs-leaf',
    'IngIndustrial': 'bx bxs-cog',
    'CompIA': 'bx bx-desktop',
    'IngElectronica': 'bx bxs-wrench',
    'Matematicas': 'bx bxs-calculator',
}

def listar_usuarios(request):
    usuarios = Usuario.objects.all()

    # Agrega un campo 'icono' a cada usuario en función de su carrera
    for usuario in usuarios:
        usuario.icono = ICONOS_CARRERA.get(usuario.carrera, 'bx bxs-user')

    return render(request, 'pages/usuarios/lista_usuarios.html', {'usuarios': usuarios})

def principal(request):
    # Obtener las últimas 10 filas del historial
    ultimas_10_filas_historial = Historial.objects.all().order_by('-fecha_movimiento')[:10]
    
    # Calcula el total de usuarios, productos y movimientos
    total_usuarios = Usuario.objects.count()
    total_productos = Producto.objects.count()
    total_movimientos = Movimiento.objects.count()

    # Implementa la función obtener_datos_para_grafico para obtener los datos necesarios
    historial_series = obtener_datos_para_grafico()

    context = {
        'ultimas_10_filas_historial': ultimas_10_filas_historial,
        'historial_series': historial_series,
        'total_usuarios': total_usuarios,
        'total_productos': total_productos,
        'total_movimientos': total_movimientos,
    }

    return render(request, 'pages/principal/principal.html', context)

def informacion_usuario(request, usuario_id):
    usuario = get_object_or_404(Usuario, pk=usuario_id)
    return render(request, 'pages/usuarios/informacion_usuario.html', {'usuario': usuario})

def verificar_carnet(request):
    mensaje = None

    if request.method == 'POST':
        carnet = request.POST['carnet']
        usuarios = Usuario.objects.filter(carnet=carnet)

        if usuarios.exists():
            mensaje = f'El carnet {carnet} ya existe en la base de datos.'
        else:
            mensaje = f'El carnet {carnet} no existe en la base de datos.'

    return render(request, 'pages/usuarios/verificar_carnet.html', {'mensaje': mensaje})

def agregar_producto(request):
    if request.method == 'POST':
        form = ProductoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('listar_productos')
    else:
        form = ProductoForm()
    return render(request, 'pages/productos/agregar_producto.html', {'form': form})

def listar_productos(request):
    productos = Producto.objects.all()  # Recupera todos los productos de la base de datos
    return render(request, 'pages/productos/listar_productos.html', {'productos': productos})

def informacion_producto(request, producto_id):
    producto = get_object_or_404(Producto, pk=producto_id)
    return render(request, 'pages/productos/informacion_producto.html', {'producto': producto})

def entregar_producto(request):
    mensaje = None

    if request.method == 'POST':
        form = EntregaProductoForm(request.POST)
        if form.is_valid():
            usuario_id = form.cleaned_data['usuario_id']
            
            try:
                usuario = Usuario.objects.get(carnet=usuario_id)
            except Usuario.DoesNotExist:
                mensaje = 'Usuario no encontrado. Por favor, registra al usuario antes de hacer el préstamo.'
                return render(request, 'pages/productos/entregar_producto.html', {'form': form, 'mensaje': mensaje})

            productos_disponibles = Producto.objects.filter(disponible=True)
            form.fields['producto'].queryset = productos_disponibles
            
            comentario = form.cleaned_data['comentario']
            producto = form.cleaned_data['producto']

            if not producto.disponible:
                mensaje = 'El Producto no está disponible para ser entregado.'
            else:
                mensaje = ''
                producto.disponible = False
                producto.save()

                movimiento = Movimiento(usuario=usuario, producto=producto, comentario=comentario)
                movimiento.save()

                historial = Historial(
                    usuario=usuario,
                    producto=movimiento.producto,
                    tipo='Entrega',
                    fecha_movimiento=movimiento.hora_entrega,
                    comentario=movimiento.comentario)
                historial.save()

                context = {'movimiento': movimiento}
                html_content = render_to_string('correos/usuario_producto.html', context)

                # Envía un correo electrónico de confirmación con contenido HTML
                subject = 'Entrega de Producto de SERGIOPLUS'
                from_email = settings.EMAIL_HOST_USER
                recipient_list = [usuario.correo_electronico]

                send_mail(subject, '', from_email, recipient_list, fail_silently=True, html_message=html_content)

                return redirect('lista_movimientos')  # Redirigir a la lista de movimientos

    else:
        form = EntregaProductoForm()

    return render(request, 'pages/productos/entregar_producto.html', {'form': form, 'mensaje': mensaje})
           
def devolver_producto(request):
    mensaje = None

    if request.method == 'POST':
        form = DevolucionProductoForm(request.POST)
        if form.is_valid():
            producto_devuelto = form.cleaned_data['producto']

            try:
                movimiento = Movimiento.objects.get(producto=producto_devuelto)
                usuario = movimiento.usuario

                # Elimina el registro de movimiento
                movimiento.delete()

                # Crea un nuevo objeto de Historial con la información de la devolución
                historial = Historial(
                    usuario=usuario,
                    producto=producto_devuelto,
                    tipo='Devolucion',
                    fecha_movimiento=movimiento.hora_entrega)

                # Actualiza el estado del producto a disponible
                producto_devuelto.disponible = True
                producto_devuelto.save()

                # Guarda el objeto de Historial en la base de datos
                historial.save()

                mensaje = 'Producto devuelto con éxito.'
            except Movimiento.DoesNotExist:
                mensaje = 'Producto no encontrado en la lista de movimientos'
    else:
        form = DevolucionProductoForm()

    return render(request, 'pages/productos/devolver_producto.html', {'form': form, 'mensaje': mensaje})

def lista_movimientos(request):
    movimientos = Movimiento.objects.all()
    return render(request, 'pages/movimientos/lista_movimientos.html', {'movimientos': movimientos})

def informacion_movimiento(request, movimiento_id):
    movimiento = Movimiento.objects.select_related('usuario', 'producto').get(pk=movimiento_id)
    context = {'movimiento': movimiento}
    return render(request, 'pages/movimientos/informacion_movimiento.html', context)

def historial(request):
    historial = Historial.objects.all()
    return render(request, 'pages/movimientos/historial_movimientos.html', {'historial': historial})

def informacion_historial(request, historial_id):
    historial = get_object_or_404(Historial, pk=historial_id)  # Asegúrate de importar el modelo Historial
    return render(request, 'pages/movimientos/informacion_historial.html', {'historial': historial})

def eliminar_producto(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)
    producto.delete()
    return redirect('listar_productos')

def editar_producto(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)

    if request.method == 'POST':
        form = ProductoForm(request.POST, instance=producto)
        if form.is_valid():
            form.save()
            return redirect('listar_productos')
    else:
        form = ProductoForm(instance=producto)

    return render(request, 'pages/productos/editar_producto.html', {'form': form, 'producto': producto})

Aplication/templates/pages/usuarios/exportar_usuarios.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exportar Usuarios</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            margin: 50px;
        }

        h1 {
            color: #333;
        }

        button {
            padding: 10px 20px;
            font-size: 16px;
            background-color: #4CAF50;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <h1>Exportar Usuarios</h1>
    <p>Exporta los datos de usuarios en diferentes formatos.</p>
    <button onclick="exportar('excel')">Exportar a Excel</button>
    <button onclick="exportar('pdf')">Exportar a PDF</button>

    <script>
        function exportar(formato) {
            window.location.href = `/exportar-usuarios/${formato}`;
        }
    </script>
</body>
</html>

Aplication/templates/pages/usuarios/formulario_usuario.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Formulario de Usuario{% endblock %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/formulario_usuario.css' %}">
    <div class="user-info-container">
        <h1>Formulario de Usuario</h1>
        <div class="form-container">
            <form method="post" class="user-form">
                {% csrf_token %}
                
                <div class="form-group">
                    <label for="id_nombre">
                        <i class="icon bx bx-user"></i>
                        Nombre:
                    </label>
                    {{ form.nombre }}
                </div>

                <div class="form-group">
                    <label for="id_correo_electronico">
                        <i class="icon bx bx-mail-send"></i>
                        Correo Electrónico:
                    </label>
                    {{ form.correo_electronico }}
                </div>

                <div class="form-group">
                    <label for="id_carrera">
                        <i class="icon bx bx-book-open"></i>
                        Carrera:
                    </label>
                    {{ form.carrera }}
                </div>

                <div class="form-group">
                    <label for="id_carnet">
                        <i class="icon bx bx-credit-card"></i>
                        Número de Carnet:
                    </label>
                    {{ form.carnet }}
                </div>

                <br>
                <button class="button-save" type="submit">
                    <i class="icon bx bx-check"></i>
                    Guardar
                </button>
            </form>
        </div>
        <div class="image-container">
            <!-- Agrega el elemento img para mostrar el GIF -->
            <img src="{% static 'img/registros.gif' %}" alt="Registros GIF" class="registros-gif">
        </div>
    </div>
    <br><br>
{% endblock %}

Aplication/templates/pages/usuarios/informacion_usuario.html
{% extends 'base.html' %}

{% block title %}Información de Usuario{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/informacion_usuario.css' %}">
<div class="info-container">
    <div class="user-card">
        <div class="user-info">
            <h1>Información de Usuario</h1>
            <p><i class="bx bx-user"></i> <strong>Nombre:</strong> {{ usuario.nombre }}</p>
            <p><i class="bx bx-book-reader"></i> <strong>Carrera:</strong> {{ usuario.carrera }}</p>
            <p><i class="bx bx-id-card"></i> <strong>Carnet:</strong> {{ usuario.carnet }}</p>
            <p><i class="bx bx-envelope"></i> <strong>Correo Electrónico:</strong> {{ usuario.correo_electronico }}</p>
        </div>
        <br><br>
        <a href="{% url 'listar_usuarios' %}" class="button return-button"><i class="bx bx-arrow-back"></i> Volver a la Lista de Usuarios</a>
    </div>
</div>
{% endblock %}

Aplication/templates/pages/usuarios/lista_usuarios.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/lista_usuario.css' %}">

<div class="container">
    <h2>Lista de Estudiantes</h2>

    <div class="card-filtro">
        <i class='bx bx-filter-alt icon'></i>
        <select id="carrera-select">
            <option value="todos">Todos</option>
            <option value="IngAmbiental">Ing. Ambiental</option>
            <option value="IngIndustrial">Ing. Industrial</option>
            <option value="CompIA">Comp. e IA</option>
            <option value="IngElectronica">Ing. Electrónica</option>
            <option value="Matematicas">Matemáticas</option>
        </select>
        <i class='bx bx-search-alt-2 icon'></i>
        <input type="text" id="search-input" placeholder="Buscar por nombre o carnet">
    </div>


    <div class="card-container">
        {% for usuario in usuarios %}
            <div class="user-card" data-carrera="{{ usuario.carrera }}">
                <a href="{% url 'informacion_usuario' usuario.id %}" class="buttonl">
                    <i class="{{ usuario.icono }}" id="{{ usuario.carrera|lower }}-icon"></i>
                    <div class="user-info">
                        <span class="user-name">{{ usuario.nombre }}</span>
                        <hr>
                        <span class="user-carrera">{{ usuario.carrera }}</span>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>

    <script src="{% static 'js/lista_usuarios.js' %}"></script>
</div>
{% endblock %}

Aplication/templates/pages/usuarios/usuarios.html
{% extends 'base.html' %}

{% block title %}Usuarios{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/principal.css' %}">

<div class="products-container">
<h2>Opciones de Usuarios</h2>
<div class="button-container">
    <a href="{% url 'agregar_usuario' %}" class="button-card">
        <div class="card dark-blue-bg">
            <i class="bx bx-user-plus card-icon white-text"></i>
            <div class="card-text">
                <h3 class="bold-text">Agregar Estudiante</h3>
                <p>Añade un nuevo estudiante registrando algunos de sus datos al sistema.</p>
            </div>
        </div>
    </a>

    <a href="{% url 'listar_usuarios' %}" class="button-card ">
        <div class="card dark-blue-bg">
            <i class="bx bx-list-check card-icon white-text"></i>
            <div class="card-text">
                <h3 class="bold-text">Lista de Estudiantes</h3>
                <p>Ver la lista completa de estudiantes registrados.</p>
            </div>
        </div>
    </a>

    <a href="{% url 'verificar_carnet' %}" class="button-card ">
        <div class="card dark-blue-bg">
            <i class="bx bx-id-card card-icon white-text"></i>
            <div class="card-text">
                <h3 class="bold-text">Verificar Carnet</h3>
                <p>Verifica la existencia de un estudiante con su UID específico.</p>
            </div>
        </div>
    </a>
</div>
</div>
{% endblock %}

Aplication/templates/pages/usuarios/verificar_carnet.html
{% extends 'base.html' %}

{% block title %}Verificar Carnet{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/verificar_carnet.css' %}">

<div class="card-verificacion verification-container">
    <h1 class="verification-title">Verificar Carnet</h1>
    
    <div class="gif-container">
        <!-- Agrega el elemento img para mostrar el GIF -->
        <img src="{% static 'img/Carnet.gif' %}" alt="Carnet GIF" class="carnet-gif">
    </div>
    
    <form method="post" class="verification-form">
        {% csrf_token %}
        <input type="text" id="carnet" name="carnet" placeholder="Ingrese el número de carnet" autofocus>
        <button type="submit" class="verify-button">Verificar</button>
    </form>
    <p class="verification-message">{{ mensaje|default:"Esperando respuesta" }}</p>
{% endblock %}